# Use postgres/example user/password credentials
version: '3.8'

services:
    PostgreDB:
        image: postgres
        restart: always
        environment: 
            - POSTGRES_DB=UnoDB
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=test
        ports: 
            - '5432:5432'
        #volumes:
            # kropka przed ./ oznacza ściekę gdzie zostaje odplony plik komendą docker-compose up
            # - ./postgres-data:/var/lib/postgresql/data
    mqtt:
        image: eclipse-mosquitto
        ports:
            - '1883:1883'
        restart: always
        environment:
            PUID: 1883
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf