server:
  port: 9001

spring:
  datasource:
    url: ${database.url:jdbc:postgresql://localhost:5432/UnoDB}
    username: ${database.username:user}
    password: ${database.password:test}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.default_schema: uno_api
    packages-to-scan:
      - pl.polsl.UnoApi.repository.dao

logging:
  level:
    root: info

mqtt:
  username: homeassistant
  password: Da8aewetu4theiPhe8zal7ahx8aeneitoM8ni2cha5meDae3rithievooghaghig
  url: tcp://157.158.168.83:1883